# Generated by Django 3.2.9 on 2021-11-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_marks', models.CharField(max_length=7)),
                ('negative_marks', models.CharField(max_length=7)),
            ],
        ),
    ]
