# Generated by Django 3.2.9 on 2021-11-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211117_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='form1',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='index',
            name='form2',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
