# Generated by Django 3.2.9 on 2021-11-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='negative_marks',
            new_name='corr',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='positive_marks',
            new_name='neg',
        ),
    ]
